config/routes.rb
ScmRor::Application.routes.draw do
  resources :events

  resources :posts

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  match '/logout' => 'user_sessions#destroy'
  
  resources :clubs

  get "session/user_session"
  get "public/index"

  root :to => "public#index"
  
  resources :languages
  resources :users
  resource :user_sessions, :controller => :user_sessions_controller
  resource :user_session
  resource :clubs
  
  resource :membergrades do
    get 'delete'
  end

  resources :members do
    resources :arts do
      get 'generate_gradeform'
    end
  end
  
  resources :arts do
    resources :grades
  end
  
  match "/dashboard" => "dashboard#show"
  match "/contactus" => "public#contactus"

  resources :clubs do
    resources :arts do
      get 'disable'
    end
    resources :members do
      get 'member'
      get 'show'
    end
    resources :events do
      get 'events'
      get 'events_future'
    end
    member do
      get 'new_member'      
    end
    get 'edit_public'
    put 'update_public'
    get 'edit_arts'
  end
  
  # root :controller => :users, :action => :index
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  has_many :artgradelinks, :dependent => :destroy
  has_many :arts, :through => :artgradelinks
  has_many :membergrades, :dependent => :destroy
  
  default_scope order('grade_order ASC') 
  
  scope :first_grade, where('grade_order = 1').limit(1).first
      
  def as_json(options = nil)
    super( options || {only: [:id, :name, :grade_order, :language, :age_minimum, :is_presence_required, :presence_required]})
  end
   
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  
  
  def index
    @art = Art.find(params[:art_id])
    respond_to do |format|
      format.html { 
        #redirect_to(club_arts_url(@club), :notice => 'Martial Art was successfully removed.') 

      }
      format.json  { render json: @art.to_json()}
    end
  end
  
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/_grade_list.html.erb
<tr id="<%= dom_id(@membergrade) %>">
  <td><%=@membergrade.grade.name%> </td>
  <%if (@membergrade.since_date) %>
    <td><%=format_date('long',@membergrade.since_date)%></td>
  <%else%>
    <td></td>
  <%end%>
    <%if @membergrade.comments
      if (@membergrade.comments.length > 30) %>
    <td><%=@membergrade.comments.slice[0,30]%></td>
      <%else%>
    <td><%=@membergrade.comments%></td>
      <%end 
    else%>
    <td></td>
    <%end%>
    <td>
      <%= link_to image_tag("/images/icons/list-edit-small.png", :alt => t('grade.action.edit_grade')), edit_membergrades_path(@membergrade), :id => 'edit_grade_link_' + @membergrade.id.to_s, :class => 'list_button'  %>
      <%= link_to image_tag("/images/icons/list-delete-small.png", :alt => t('grade.action.delete_grade')), delete_membergrades_path(@membergrade), :id => 'delete_grade_link_' + @membergrade.id.to_s, :class => 'list_button'  %>

    </td>  
</tr>

app/views/grades/_grades_list.html.erb
<table class="table">
  <tr>
    <th><%=t('grade.name')%></th>
    <th><%=t('grade.assessment_date')%></th>
    <th><%=t('grade.assessment_comments')%></th>
    <th><%=t('grade.actions')%></th>
  </tr>
  <% membergrades.each do |mg| %>
    <tr id="<%= dom_id(mg) %>">
      <td><%=mg.grade.name%> </td>
      <%if (mg.since_date) %>
        <td><%=format_date('long',mg.since_date)%></td>
      <%else%>
        <td></td>
      <%end%>
        <%if mg.comments
          if (mg.comments.length > 30) %>
        <td><%=mg.comments.slice[0,30]%></td>
          <%else%>
        <td><%=mg.comments%></td>
          <%end 
        else%>
        <td></td>
        <%end%>
        <td>
          <%= link_to image_tag("/images/icons/list-edit-small.png", :alt => t('grade.action.edit_grade')), edit_membergrades_path(mg), :id => 'edit_grade_link_' + mg.id.to_s, :class => 'list_button'  %>
          <%= link_to image_tag("/images/icons/list-delete-small.png", :alt => t('grade.action.delete_grade')), delete_membergrades_path(mg), :id => 'delete_grade_link_' + mg.id.to_s, :class => 'list_button'  %>
              
        </td>  
    </tr>
  <%  end%>
    
</table>

app/views/grades/_member_grade_form.html.erb
<h2> <%= t('grade.title.new') %> </h2>
<div id="member_error"></div>
<% today = Date.today %>
<%= semantic_form_for [@membergrade], :remote => true do |f| %>

    <%= f.input :member_id, :as => :hidden, :value => params[:member_id] %>
    <%= f.input :art_id, :as => :hidden, :value => params[:art_id] %>
    <%= f.input :grade_id, :as => :select, :collection => @available_grades%>
    <%= f.input :since_date, :as => :date, :label => t('grade.assessment_date'), :start_year => today.year, :end_year => today.year - 30 %>
    <%= f.input :is_actual, :as => :boolean, :value => true, :label => t('grade.present_grade'), :input_html => { :checked => 'checked' } %>
    <%= f.input :comments, :as => :text , :label => t('grade.assessment_comments') %>

  <%= f.buttons do %>
    <%= f.commit_button  t('grade.action.save_button'), :button_html => {:id => "create_grade_submit_button",  :class => "form_submit" } %>
    <div class="ajax-loader-wrapper hidden">
      <img src="/images/ajax-loader-small.gif"/>
    </div>
  <% end %>
<% end %>

app/views/grades/create.js.erb
(function($) {
    
    <% if @membergrade.new_record?  %>
      var $error_field = $('#member_error').html('');
      var $form = $('#new_membergrade');
      $form.find(".error").removeClass("error");
              
      <% @membergrade.errors.each do |er| %>
          $form.find("select[name='membergrade[<%= er %>]']").addClass("error");
          if ('<%= er %>' == 'since_date'){
            $form.find("select[name='membergrade[since_date(1i)]']").addClass("error");
            $form.find("select[name='membergrade[since_date(2i)]']").addClass("error");
            $form.find("select[name='membergrade[since_date(3i)]']").addClass("error");
          }
      <% end %>
    <% else %>
    
      $('div#art_table_<%=@membergrade.art_id%> > table > tbody >tr:last').after("<%= escape_javascript(render :partial => "grades/grade_list", :layout => false) %>"); 
      $('div#art_table_<%=@membergrade.art_id%> > table > tbody >tr:last').addClass('newly_added');

      $('#mask').fadeOut(200);
      $('#dialog_form').fadeOut(200, function(){
        $('#div#grade_create').html('');
      });
    
    <%end%>
})(jQuery);